# Example usage

version: '3.8'

services:
  caddy:
    image: ghcr.io/williamjacksn/caddy-route53
    environment:
      AWS_ACCESS_KEY_ID: (set in docker-compose.override.yaml)
      AWS_SECRET_ACCESS_KEY: (set in docker-compose.override.yaml)
    volumes:
      - caddy-data:/data
      - ./caddy:/etc/caddy
    ports:
      - 80:80
      - 443:443

volumes:
  caddy-data:
